---
hmg: "http://hmg.nflix.com"
database: 
  host: "192.168.99.100"
  dbname: "nflix"
  user: "postgres"
  password: "qaninja"
users:
  cat_manager:
    email: 'pepper.tonks@stark.com'
    pass: "pwd123"